// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmi1Vk2eftba7vbjBtMk2r7OrMein51YE',
    appId: '1:378389509758:web:8c079d3d2d075f8051ca2f',
    messagingSenderId: '378389509758',
    projectId: 'chatapp-7faa9',
    authDomain: 'chatapp-7faa9.firebaseapp.com',
    storageBucket: 'chatapp-7faa9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZoN0kD2EGuYNnRQtrlLFeDFyzhtLXCBk',
    appId: '1:378389509758:android:896c0f949fe54ee651ca2f',
    messagingSenderId: '378389509758',
    projectId: 'chatapp-7faa9',
    storageBucket: 'chatapp-7faa9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAg1uFBQSi-ZB-My4AUsxgIOUCxvFb_xxs',
    appId: '1:378389509758:ios:d462a2dded44f78251ca2f',
    messagingSenderId: '378389509758',
    projectId: 'chatapp-7faa9',
    storageBucket: 'chatapp-7faa9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAg1uFBQSi-ZB-My4AUsxgIOUCxvFb_xxs',
    appId: '1:378389509758:ios:8efe22074f5087ad51ca2f',
    messagingSenderId: '378389509758',
    projectId: 'chatapp-7faa9',
    storageBucket: 'chatapp-7faa9.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
